version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"  # Use the default MongoDB port
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379" # Redis default port
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongodb_data:
  redis_data:
