groups:
  - name: lintern-alerts
    rules:
      # High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(lintern_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      # High Response Time Alert
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(lintern_http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # Redis Connection Alert
      - alert: RedisConnectionIssue
        expr: redis_up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection lost"
          description: "Redis is unreachable"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Queue Job Failure Alert
      - alert: HighQueueJobFailureRate
        expr: rate(lintern_queue_jobs_total{status="failed"}[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High queue job failure rate"
          description: "Queue job failure rate is {{ $value }} failures per second"

      # Database Query Performance Alert
      - alert: SlowDatabaseQueries
        expr: histogram_quantile(0.95, rate(lintern_db_query_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile DB query time is {{ $value }} seconds"