export enum CompanyActionType {
  CREATION_OFFRE_EMPLOI = 'création_offre_emploi',
  MODIFICATION_OFFRE_EMPLOI = 'modification_offre_emploi',
  SUPPRESSION_OFFRE_EMPLOI = 'suppression_offre_emploi',
  CONSULTATION_PROFIL_CANDIDAT = 'consultation_profil_candidat',
  PLANIFICATION_ENTRETIEN = 'planification_entretien',
  MODIFICATION_ENTRETIEN = 'modification_entretien',
  ANNULATION_ENTRETIEN = 'annulation_entretien',
  CHANGEMENT_STATUT_CANDIDATURE = 'changement_statut_candidature',
  INVITATION_UTILISATEUR = 'invitation_utilisateur',
  MODIFICATION_PROFIL_ENTREPRISE = 'modification_profil_entreprise',
  CONNEXION = 'connexion',
  DECONNEXION = 'déconnexion',
  RECEPTION_CANDIDATURE = 'réception_candidature',
}

export enum CandidateActionType {
  MISE_A_JOUR_PROFIL = 'mise_à_jour_profil',
  AJOUT_EXPERIENCE = 'ajout_expérience',
  MODIFICATION_EXPERIENCE = 'modification_expérience',
  SUPPRESSION_EXPERIENCE = 'suppression_expérience',
  AJOUT_FORMATION = 'ajout_formation',
  MODIFICATION_FORMATION = 'modification_formation',
  SUPPRESSION_FORMATION = 'suppression_formation',
  AJOUT_CERTIFICATION = 'ajout_certification',
  MODIFICATION_CERTIFICATION = 'modification_certification',
  SUPPRESSION_CERTIFICATION = 'suppression_certification',
  MISE_A_JOUR_COMPETENCES = 'mise_à_jour_compétences',
  ENVOI_CANDIDATURE = 'envoi_candidature',
  RETRAIT_CANDIDATURE = 'retrait_candidature',
  NOTIFICATION_ACCEPTATION = 'notification_acceptation',
  NOTIFICATION_REJET = 'notification_rejet',
  TELECHARGEMENT_CV = 'téléchargement_cv',
  ENTRETIEN_CONFIRME = 'entretien_confirmé',
  CONNEXION = 'connexion',
  DECONNEXION = 'déconnexion',
}