export enum Benefit {
  HEALTH_INSURANCE = 'HEALTH_INSURANCE',
  CAREER_GROWTH = 'CAREER_GROWTH',
  TRAINING = 'TRAINING',
  FLEXIBLE_HOURS = 'FLEXIBLE_HOURS',
  REMOTE_WORK = 'REMOTE_WORK',
  COMPETITIVE_SALARY = 'COMPETITIVE_SALARY',
  PERFORMANCE_BONUS = 'PERFORMANCE_BONUS',
  TEAM_BUILDING = 'TEAM_BUILDING',
  PARKING = 'PARKING',
  CAFETERIA = 'CAFETERIA'
}
