export enum ProfessionalStatus {
  ACTIVELY_SEEKING = 'ACTIVELY_SEEKING',
  PASSIVELY_LOOKING = 'PASSIVELY_LOOKING',
  EMPLOYED = 'EMPLOYED',
  CONTRACTOR = 'CONTRACTOR',
  FREELANCER = 'FREELANCER',
  CONSULTANT = 'CONSULTANT',
  NOT_AVAILABLE = 'NOT_AVAILABLE'
}